[package]
name = "gpui-form-derive"
description = """
Macro crate for gpui-form
"""
version = "0.5.1"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/hmziqrs/gpui-starter"

[lib]
proc-macro = true

[features]
default = [  ]
inventory = [  ]

[dependencies]
darling = { workspace = true }
es-fluent = { workspace = true }
gpui-form-codegen = { workspace = true }
itertools = { workspace = true }
koruma-derive-core = { workspace = true }
proc-macro-error2 = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { features = [ "full" ], workspace = true }
syn-cfg-attr = { workspace = true }

[dev-dependencies]
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-form = { default-features = false, path = "../gpui-form" }
insta = { workspace = true }
koruma = { workspace = true }
koruma-collection = { workspace = true }
prettyplease = { workspace = true }
trybuild = "1.0"
