#!/usr/bin/env bash
#
# Generate a PKGBUILD for the gpui-starter Linux release tarball.
#
# Arch Linux users (and AUR packagers) consume the prebuilt linux tarball
# produced by the release workflow via this PKGBUILD. It downloads the
# architecture-appropriate tarball from the GitHub Release, installs the
# binary + bundled libs into /usr, and writes a .desktop entry + icon.
#
# Usage:
#   scripts/gen-pkgbuild.sh <version> <arch-tarball-name>
#     <version>            bare X.Y.Z (e.g. 0.2.0)
#     <arch-tarball-name>  e.g. gpui-starter-0.2.0-x86_64-linux.tar.gz
#
# Writes the PKGBUILD to stdout (redirect to a file in the release step).
set -euo pipefail

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <version> <arch-tarball-name>" >&2
  exit 1
fi

VERSION="$1"
TARBALL="$2"

# Validate X.Y.Z (reuse the shared normalizer's regex shape).
if ! printf '%s' "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
  echo "Error: invalid version '$VERSION' (expected X.Y.Z)" >&2
  exit 1
fi

# Derive the pkgarch from the tarball name (x86_64 -> x86_64, aarch64 -> aarch64).
if printf '%s' "$TARBALL" | grep -q 'x86_64'; then
  PKGARCH="x86_64"
elif printf '%s' "$TARBALL" | grep -q 'aarch64'; then
  PKGARCH="aarch64"
else
  echo "Error: could not infer arch from tarball name '$TARBALL'" >&2
  exit 1
fi

cat <<PKGBUILD
# Generated by scripts/gen-pkgbuild.sh — do not edit by hand.
# Maintainer: gpui-starter contributors

pkgname=gpui-starter
pkgver=${VERSION}
pkgrel=1
pkgdesc="A starter application built on the GPUI framework (Zed's UI toolkit)"
arch=('${PKGARCH}')
url="https://github.com/\${REPO:-zed-industries/gpui-starter}"
license=('MIT')
depends=('vulkan-driver' 'libxkbcommon-x11' 'wayland' 'fontconfig' 'freetype2')
provides=('gpui-starter')
conflicts=('gpui-starter')

# The release workflow publishes this architecture-specific tarball to the
# GitHub Release; makepkg fetches it by its real name ($TARBALL expands here,
# \${REPO} stays literal for the packager to override).
source=("${TARBALL}::https://github.com/\${REPO:-zed-industries/gpui-starter}/releases/download/v${VERSION}/${TARBALL}")
sha256sums=('SKIP')  # verified via the signed update manifest / GitHub Release checksums

package() {
    install -Dm755 "gpui-starter" "\${pkgdir}/usr/bin/gpui-starter"

    # Bundled shared libraries (patchelf rpath = \$ORIGIN/lib). Install them
    # next to the binary so the relinked rpath resolves without a system lib.
    if [ -d "lib" ]; then
        install -dm755 "\${pkgdir}/usr/lib/gpui-starter"
        cp -a lib/. "\${pkgdir}/usr/lib/gpui-starter/"
    fi

    install -Dm644 "LICENSE" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
    install -Dm644 "README.md" "\${pkgdir}/usr/share/doc/\${pkgname}/README.md"

    install -Dm644 /dev/stdin "\${pkgdir}/usr/share/applications/gpui-starter.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=GPUI Starter
Comment=\${pkgdesc}
Exec=gpui-starter %U
Icon=gpui-starter
Categories=Development;
Terminal=false
MimeType=x-scheme-handler/gpui-starter;
DESKTOP
}
PKGBUILD
