[package]
name = "gpui-form"
description = """
The gpui-form crate
"""
version = "0.5.1"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/hmziqrs/gpui-starter"
keywords = [ "gpui", "gpui-component", "form" ]

[features]
default = [ "derive" ]
derive = [ "dep:gpui-form-derive", "gpui-form-component/derive" ]
inventory = [ "gpui-form-derive?/inventory" ]

[dependencies]
bon = { workspace = true }
gpui-form-component = { workspace = true }
gpui-form-core = { workspace = true }
gpui-form-derive = { optional = true, workspace = true }
gpui-form-schema = { workspace = true }
